
import com.formdev.flatlaf.FlatLightLaf;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.*;

public class RegistroUtilizador extends javax.swing.JFrame {
    /** Creates new form RegistroUtilizador */
    public RegistroUtilizador() {
         try {
            FlatLightLaf.setup();
        } catch (Exception ex) {
        }
        initComponents();
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception ex) {
            Logger.getLogger(RegistroUtilizador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ctxemail = new javax.swing.JTextField();
        ctxnome = new javax.swing.JTextField();
        ctxmorada = new javax.swing.JTextField();
        ctxtelef = new javax.swing.JTextField();
        ctxnif = new javax.swing.JTextField();
        ctxlogin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ctxpass = new javax.swing.JPasswordField();
        ctxrepass = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulário de Registro de Utilizador");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Registro de Utilizador");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("NIF");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Morada");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Telefone");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Reescreva Password");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Password");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Login");

        ctxemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxemailActionPerformed(evt);
            }
        });

        ctxmorada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxmoradaActionPerformed(evt);
            }
        });

        ctxtelef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxtelefActionPerformed(evt);
            }
        });

        ctxnif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxnifActionPerformed(evt);
            }
        });

        ctxlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxloginActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Mostrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setText("Mais de 8 de comprimento e pelo menos um de cada: a-z, A-Z, 0-9, caracteres especiais");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton4.setText("Mostrar Registros");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel9)
                            .add(jLabel4)
                            .add(jLabel6)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(jLabel5)
                            .add(layout.createSequentialGroup()
                                .add(jLabel8)
                                .add(69, 69, 69)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(ctxlogin)
                                    .add(ctxnif)
                                    .add(ctxtelef)
                                    .add(ctxmorada)
                                    .add(ctxemail)
                                    .add(ctxnome)
                                    .add(ctxpass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 291, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton3))
                            .add(layout.createSequentialGroup()
                                .add(jLabel7)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(ctxrepass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 292, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(0, 0, Short.MAX_VALUE))
                                    .add(layout.createSequentialGroup()
                                        .add(jButton1)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jButton2)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 184, Short.MAX_VALUE)
                                        .add(jButton4))))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(151, 151, 151)
                        .add(jLabel10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(ctxnome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(ctxemail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(ctxmorada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(ctxtelef, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(ctxnif, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(ctxlogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(ctxpass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel10)
                .add(7, 7, 7)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(ctxrepass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton1)
                    .add(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void ctxemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxemailActionPerformed
    }//GEN-LAST:event_ctxemailActionPerformed

    private void ctxmoradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxmoradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxmoradaActionPerformed

    private void ctxtelefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxtelefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxtelefActionPerformed

    private void ctxnifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxnifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxnifActionPerformed

    private void ctxloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxloginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mostraMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Erro de Registro", JOptionPane.ERROR_MESSAGE);
    }
    
    private static final Pattern NINE_NUMBER_PATTERN = Pattern.compile("[0-9]{9}");
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s = "";
        int conta = 0, contaEspacos = 0;
        boolean nome = false;
        boolean email = false;
        boolean morada = false;
        boolean telefone = false;
        boolean nif = false;
        boolean login = false;
        boolean pass = false;
        boolean repass = false;
        
        if (this.ctxnome.getText().equals("")) {
            this.mostraMessage("Preencha o campo nome!");
        } else {
            if (this.ctxnome.getText().length() < 2) {
                this.mostraMessage("Preencha um nome válido");
            } else {
                for (int i = 0; i < this.ctxnome.getText().length(); ++i) {
                    if (Character.isLetter(this.ctxnome.getText().charAt(i))) {
                        ++conta;
                    }
                }
                if (conta < 2) {
                    this.mostraMessage("Preencha um nome válido");
                } else {
                    for (int i = 0; i < this.ctxnome.getText().length(); ++i) {
                        if ((this.ctxnome.getText().charAt(i) >= 65 && this.ctxnome.getText().charAt(i) <= 90)
                                || this.ctxnome.getText().charAt(i) >= 97 && this.ctxnome.getText().charAt(i) <= 122) {
                            ++conta;
                        } else if (this.ctxnome.getText().charAt(i) == ' ') {
                            ++contaEspacos;
                        }
                    }
                    
                    if (conta < 2 || (conta + contaEspacos) <  this.ctxnome.getText().length()) {
                        this.mostraMessage("Preencha um nome válido");
                    } else {
                        nome = true;
                    }
                }
            }
        }
        
        // validar email
        if (nome) {
            s = this.ctxemail.getText();
            
            if (s.equals("")) {
                this.mostraMessage("Preencha o campo email!");
            } else {
                if (!s.matches("[a-zA-Z_0-9.]{2,}@[a-zA-Z_0-9.]{2,}\\.[a-zA-Z_0-9.]{2,}")) {
                    this.mostraMessage("Preencha um email válido!");
                } else {
                    email = true;
                }
            }
        }
        
        // validar morada
        if (email) {
            s = this.ctxmorada.getText();
            if (s.equals("")) {
                this.mostraMessage("Preencha o campo morada!");
            } else {
                morada = true;
            }
        }
        
        // validar telefone
        if (morada) {
            s = this.ctxtelef.getText();
            if (s.equals("")) {
                this.mostraMessage("Preencha o campo telefone!");
            } else {
                if (s.matches("[0-9]{9}")) {
                    nif = true;
                } else {
                    this.mostraMessage("Preencha um telefone válido!");
                }
            }
        }
        
        // validar nif
        if (telefone) {
            s = this.ctxnif.getText();
            if (s.equals("")) {
                this.mostraMessage("Preencha o campo NIF!");
            } else {
                if (s.matches("[0-9]{9}")) {
                    nif = true;
                } else {
                    this.mostraMessage("Preencha um nif válido!");
                }
            }
        }
        
        // validar login
        if (nif) {
            s = this.ctxlogin.getText();
            if (s.equals("")) {
                this.mostraMessage("Preencha o campo login!");
            } else {
                if (s.indexOf(' ') >= 0) {
                    this.mostraMessage("Preencha um login válido!");
                } else {
                    login = true;
                }
            }
        }
        
        // validar password
        if (login) {
            char[] passArr = this.ctxpass.getPassword();
            if (passArr.length == 0) {
                this.mostraMessage("Preencha o campo password!");
            } else {
                String passStr = new StringBuilder().append(passArr).toString();
                if (passStr.matches("^(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\\w\\d\\s:])([^\\s]){8,}$")) {
                    pass = true;
                } else {
                    this.mostraMessage("Preencha uma password válida!");
                }
            }
        }
        
        // validar reescrever password
        if (pass) {
            if (Arrays.equals(this.ctxrepass.getPassword(), this.ctxpass.getPassword())) {
                repass = true;
            } else {
                this.mostraMessage("As passwords têm de corresponder!");
            }
        }
        
        if (repass) {
            
            User utilizador = new User(this.ctxnome.getText(), this.ctxemail.getText(), this.ctxmorada.getText(),
                                            this.ctxtelef.getText(), this.ctxnif.getText(), this.ctxlogin.getText(),
                                            this.ctxpass.getText());
            UserDataBase.getSQL().addUser(utilizador);
            JOptionPane.showMessageDialog(this, "Utilizador adicionado!", "Registro de Utilizador", JOptionPane.INFORMATION_MESSAGE);
            this.clearFormEntries();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void clearFormEntries() {
        this.ctxnome.setText("");
        this.ctxemail.setText("");
        this.ctxmorada.setText("");
        this.ctxtelef.setText("");
        this.ctxnif.setText("");
        this.ctxlogin.setText("");
        this.ctxpass.setText("");
        this.ctxrepass.setText("");
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (this.ctxpass.getEchoChar() == '\u0000') {
            this.ctxpass.setEchoChar('*');
            this.jButton3.setText("Mostrar");
        } else {
            this.ctxpass.setEchoChar('\u0000');
            this.jButton3.setText("Esconder");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new MostraFicheiros().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUtilizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ctxemail;
    private javax.swing.JTextField ctxlogin;
    private javax.swing.JTextField ctxmorada;
    private javax.swing.JTextField ctxnif;
    private javax.swing.JTextField ctxnome;
    private javax.swing.JPasswordField ctxpass;
    private javax.swing.JPasswordField ctxrepass;
    private javax.swing.JTextField ctxtelef;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
