package dev.biblioteca.dialog;

import dev.biblioteca.Leitor;
import dev.biblioteca.bd.LigaBD;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RegistoLeitores extends javax.swing.JDialog {
    /**
     * Creates new form RegistroLeitores
     */
    private Runnable updateFunc;
    private int selectedRow;
    
    public RegistoLeitores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.load();
        this.table.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                selectedRow = table.getSelectedRow();
                String nleitor = (String) model.getValueAt(selectedRow, 1);
                
                Leitor leitor = null;
                for (Leitor l : LigaBD.getBD().obterLeitors()) {
                    if (l.getNleitor().equals(nleitor)) {
                        leitor = l;
                        break;
                    }
                }
                
                if (LigaBD.FUNCIONARIO_LOGGED && leitor != null && leitor.getLivroRequesitados().isEmpty()) {
                    removeLeitorButton.setEnabled(true);
                } else {
                     removeLeitorButton.setEnabled(false);
                }
            }
            
        });
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                LigaBD.LOGIN_STATUS_CHANGE_EVENT.unregister(RegistoLeitores.this::onLoginStatusChange);
                LigaBD.LEITORES_UPDATE_EVENT.unregister(RegistoLeitores.this.updateFunc);
            }
            
        });
        this.updateFunc = () -> {
            this.load();
        };
        LigaBD.LEITORES_UPDATE_EVENT.register(this.updateFunc);
        LigaBD.LOGIN_STATUS_CHANGE_EVENT.register(this::onLoginStatusChange);
        this.onLoginStatusChange();
        this.removeAllButton.setVisible(false);
    }
    
    private void onLoginStatusChange() {
        this.removeAllButton.setEnabled(LigaBD.FUNCIONARIO_LOGGED);
    }
    
    private void load() {
        DefaultTableModel model = (DefaultTableModel) this.table.getModel();
        this.clearTableData(model);
        List<Leitor> leitores = LigaBD.getBD().obterLeitors();
        for (Leitor leitor : leitores) {
            List<String> livros = leitor.getLivroRequesitados();
            String lvs = "";
            for (String titulo : livros) {
                lvs += titulo + " ; ";
            }
            
            model.addRow(new Object[] { leitor.getNome(), leitor.getNleitor(), leitor.getTelefone(), leitor.getEmail(), leitor.getLogin(), lvs });
        }
        this.setTitle("Registo de Leitores (" + leitores.size() + ")");
    }
    
    private void clearTableData(DefaultTableModel tableModel) {
        for (int rowCount = tableModel.getRowCount(), i = rowCount - 1; i >= 0; --i) {
            tableModel.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        removeAllButton = new javax.swing.JButton();
        removeLeitorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registo de Leitores");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Nº de Leitor", "Telefone", "Email", "Nome de Utilizador", "Livros"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);

        removeAllButton.setText("Remover Todos");

        removeLeitorButton.setText("Remover");
        removeLeitorButton.setEnabled(false);
        removeLeitorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLeitorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removeAllButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeLeitorButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeAllButton)
                    .addComponent(removeLeitorButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeLeitorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLeitorButtonActionPerformed
        // TODO add your handling code here:
        String[] opcoes = {"Continuar", "Cancelar"};
        int resposta = JOptionPane.showOptionDialog(this, "Tem certeza de que deseja realizar esta ação?", "Confirmação", 
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[1]);
        if (resposta== JOptionPane.YES_OPTION){
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            LigaBD.getBD().excluirLeitor((String) model.getValueAt(this.selectedRow, 1));
            LigaBD.ACTION_MESSAGE_EVENT.invoker().run("Removido leitor '" + ((String) model.getValueAt(this.selectedRow, 0)) + "'");
            model.removeRow(this.selectedRow);
            this.removeLeitorButton.setEnabled(false);
        }
    }//GEN-LAST:event_removeLeitorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistoLeitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistoLeitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistoLeitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistoLeitores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistoLeitores dialog = new RegistoLeitores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeAllButton;
    private javax.swing.JButton removeLeitorButton;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
